---
title: "R Notebook"
output: html_notebook
---

### Joining datasets

#### 1. Join hazard history and service requests to get a list of requests made during and 24 hours after a severe weather event

```{r}
library(data.table)
setDT(service_requests)
setDT(hazard_history)

storm_service_requests <- hazard_history[service_requests,
                                 on = .(storm_start_date <= service_request_datetime, window_end >= service_request_datetime),
                                 nomatch = 0, 
                                 allow.cartesian = TRUE]
```

```{r}
#select relevant variables
storm_service_requests <- storm_service_requests %>%
  select("storm_event_id", "storm_date", "storm_duration", "storm_name", "storm_issues", "daily_total_rainfall", "rainfall_rate", "total_snowfall", "wind_speed", "tree_condition", "borough", "address", "service_request_date", "geometry")
```

#### 2. Join storm service requests with tree map data to get species and size of each serviced tree

```{r}
#join by nearest feature - matches serviced tree locations (planting spaces) to the closest tree coordinates given in the tree map
storm_service_requests <- st_as_sf(storm_service_requests)

serviced_trees <- st_join(storm_service_requests, tree_map, join = st_nearest_feature)
```

```{r}
#selecting and rearranging relevant columns
serviced_trees <- serviced_trees %>%
  select("tree_id", "species_common", "species_scientific", "stump_diameter", "tree_condition", "borough", "closest_address", "geometry", "service_request_date", "storm_date", "storm_event_id", "storm_issues", "daily_total_rainfall", "rainfall_rate", "total_snowfall", "wind_speed")
```

```{r}
#reformatting dates to be POSIXct objects
serviced_trees$service_request_date <- ymd_hms(serviced_trees$service_request_date)
serviced_trees$storm_date <- mdy_hm(serviced_trees$storm_date)
```

```{r}
#merge rows that were counted twice, since some storms happened within 24 hours of each other
serviced_trees <- serviced_trees %>%
  distinct(geometry, service_request_date, .keep_all = TRUE)
```

```{r}
# simplify categories of damage
serviced_trees <- serviced_trees %>%
  mutate(tree_condition = case_when(
    grepl("Limb Down", tree_condition) ~ "Limb Down",
    grepl("Tree Down", tree_condition) ~ "Tree Down",
    grepl("Hanging Limb", tree_condition) ~ "Limb Down",
    grepl("Poor Condition ", tree_condition) ~ "Poor Condition",
    grepl("Tree Uprooted", tree_condition) ~ "Tree Down",  
    TRUE ~ tree_condition))
```

```{r}
#save files
write.csv(storm_service_requests, "storm_service_requests.csv", row.names = FALSE)
write.csv(serviced_trees, "serviced_trees.csv", row.names = FALSE)
```

\
Filtering down to approved tree species

```{r}
approved_species <- read.csv("nyc_approved_species.csv")
```

```{r}
approved_genus_only <- approved_species$species_scientific[str_count(approved_species$species_scientific, "\\S+") == 1] 
approved_full_species <- approved_species$species_scientific[str_count(approved_species$species_scientific, "\\S+") > 1]  
```

```{r}
approved_all_genera <- unique(c(
  approved_genus_only,
  word(approved_full_species, 1)
))
```

```{r}
tree_map_genera <- tree_map_metrics %>%
  mutate(genus = word(species_scientific, 1))
```

```{r}
trees_approved <- tree_map_genera %>%
  filter(
    species_scientific %in% approved_full_species |                          # rule 1: exact species match
  genus %in% approved_genus_only |                                          # rule 2: whole genus approved
  (species_scientific == genus & genus %in% approved_all_genera)            # rule 3: genus-only record, genus represented on approved list
)
```

```{r}
#filtering down to approved tree species only
serviced_trees_approved <- trees_approved %>%
  filter(trees_approved$serviced == "1")
```

```{r}
# adding NTA names to dataset
trees_approved <- st_as_sf(trees_approved)
trees_approved <- st_transform(trees_approved, st_crs(neighborhood_boundaries))

trees_approved <- st_join(trees_approved, neighborhood_boundaries, join = st_within)
```

```{r}
trees_approved <- trees_approved %>%
  select("tree_id", "species_common", "species_scientific", "genus", "stump_diameter", "height", "crown_diameter", "closest_address", "serviced", "ntaname", "geometry")
```
