---
title: "introductory_tables" output: html_document ---
---

```{r}
library(ggplot2)
```

```{r}
# create table of top 30 street tree species in NYC
street_tree_counts <- tree_map %>%
  group_by(species_scientific) %>%
  summarise(frequency = n()) %>%
  arrange(desc(frequency))

street_tree_counts$geometry <- NULL

top30_street_trees <- street_tree_counts %>%
  slice_max(frequency, n = 30)
```

```{r}
# create table of top 30 serviced tree species in NYC
serviced_tree_counts <- serviced_trees %>%
  group_by(species_scientific) %>%
  summarise(frequency = n()) %>%
  arrange(desc(frequency))

serviced_tree_counts$geometry <- NULL

#cut to top 15
top30_serviced_trees <- serviced_tree_counts %>%
  slice_max(frequency, n = 30)
```

```{r}
#bar graph of top 30 street tree species
top30_street_trees %>%
  ggplot(aes(x = reorder(species_scientific, frequency), y=frequency)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = "Top 30 NYC Street Tree Species", x = "Species", y = "Number of trees")
```

```{r}
#bar graph of top 30 serviced trees
top30_serviced_trees %>%
  ggplot(aes(x = reorder(species_scientific, frequency), y=frequency)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = "Top 30 Serviced Tree Species", x = "Species", y = "Number of trees")
```

```{r}
# get list of approved street trees for planting
nyc_approved_trees <- read.csv("nyc_approved_trees.csv")
```

```{r}
# create graph of the frequency of each approved street tree in NYC

approved_tree_frequency <- semi_join(street_tree_counts, nyc_approved_trees, by = "species_scientific")

approved_tree_frequency %>%
  ggplot(aes(x = reorder(species_scientific, frequency), y=frequency)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = "Approved Tree Species Counts", x = "Species", y = "Number of trees") +
  theme(axis.text.y = element_text(size = 6))
```

```{r}
# Top 30 street trees, highlighting the approved species
top30_street_trees <- top30_street_trees %>%
  mutate(highlight = ifelse(species_scientific %in% nyc_approved_trees$species_scientific, 
                             "Approved", "Not approved"))

ggplot(top30_street_trees, aes(x = reorder(species_scientific, frequency), y = frequency, fill = highlight)) +
  geom_bar(stat = "identity") +  coord_flip() +
  scale_fill_manual(values = c("Approved" = "forestgreen", "Not approved" = "grey75")) +
  theme_minimal() +
   labs(title = "Top 30 Street Tree Species", x = "Species", y = "Number of trees")
```

```{r}
top30_serviced_trees <- top30_serviced_trees %>%
  mutate(highlight = ifelse(species_scientific %in% nyc_approved_trees$species_scientific, 
                             "Approved", "Not approved"))

# Plot
ggplot(top30_serviced_trees, aes(x = reorder(species_scientific, frequency), y = frequency, fill = highlight)) +
  geom_bar(stat = "identity") +  coord_flip() +
  scale_fill_manual(values = c("Approved" = "forestgreen", "Not approved" = "grey75")) +
  theme_minimal() +
   labs(title = "Top 30 Serviced Tree Species", x = "Species", y = "Number of trees")
```

```{r}
# Create graph of service requests by borough
servicerequest_location <- serviced_trees %>%
  group_by(borough) %>%
  summarise(frequency = n()) %>%
  arrange(desc(frequency))

servicerequest_location %>%
  ggplot(aes(x = reorder(borough, frequency), y=frequency)) +
  geom_bar(stat = "identity") +
  coord_flip() +
   labs(title = "Service Requests by Borough", x = "Borough", y = "Number of service requests")
```

#### Getting simple ratios of each species to the totals

```{r}
#ratio of each species to the total number of trees in NYC
total_tree_ratios <- street_tree_counts %>%
  mutate(
    total = sum(frequency),
    ratio = frequency / 703283, percentage = round(ratio * 100, 2)
  )
```

```{r}
# ratio of each serviced species count to the total number of serviced trees
serviced_tree_ratios <- serviced_tree_counts %>%
  mutate(
    total = sum(frequency),
    ratio = frequency / 29436, percentage = round(ratio * 100, 2)
  )
```

```{r}
# ratio of serviced trees for each population to total species population
serviced_species_ratios <- serviced_tree_counts %>% left_join (street_tree_counts, by = "species_scientific")

serviced_species_ratios <- serviced_species_ratios %>%
  mutate(ratio = frequency.x / frequency.y, 
percentage = round(ratio * 100, 2))
# e.g. 36% of populus tremoides were damaged
```

#### Repeating everything, but grouped by genus

```{r}
serviced_tree_genus_counts <- serviced_tree_counts %>%
  mutate(genus = word(species_scientific, 1)) %>%
  group_by(genus) %>%
  summarise(frequency = sum(frequency)) %>%
  arrange(desc(frequency))
```

```{r}
street_tree_genus_counts <- street_tree_counts %>%
  mutate(genus = word(species_scientific, 1)) %>%
  group_by(genus) %>%
  summarise(frequency = sum(frequency)) %>%
  arrange(desc(frequency))
```

```{r}
serviced_genus_ratios <- serviced_tree_genus_counts %>% left_join (street_tree_genus_counts, by = "genus")

serviced_genus_ratios <- serviced_genus_ratios %>%
  mutate(ratio = frequency.x / frequency.y, 
percentage = round(ratio * 100, 2))
```

```{r}
total_genus_ratios <- street_tree_genus_counts %>%
  mutate(
    total = sum(frequency),
    ratio = frequency / 703283, percentage = round(ratio * 100, 2)
  )
```

```{r}
serviced_genus_ratios_total <- serviced_tree_genus_counts %>%
  mutate(
    total = 29436,
    ratio = frequency / total, percentage = round(ratio * 100, 2)
  )
```

#### Categorizing trees by damage intensity and storm intensity

```{r}
serviced_trees_damage <- serviced_trees %>%
  select("tree_id", "species_scientific", "geometry", "storm_issues", "tree_condition")
```

```{r}
# renaming categories to combine them
serviced_trees_damage <- serviced_trees_damage %>%
  mutate(tree_condition = case_when(
    grepl("Limb Down", tree_condition) ~ "Limb Down",
    grepl("Tree Down", tree_condition) ~ "Tree Down",
    grepl("Hanging Limb", tree_condition) ~ "Limb Down",
    grepl("Poor Condition ", tree_condition) ~ "Poor Condition",
    grepl("Tree Uprooted", tree_condition) ~ "Tree Down",  
    TRUE ~ tree_condition))
```

```{r}
#create contingency table of species and damage types
cont_table <- (table(serviced_trees_damage$species_scientific, serviced_trees_damage$tree_condition))
```

```{r}
#frequency table and graph of damage intensity
damage_frequency <- serviced_trees_damage %>%
  group_by(tree_condition) %>%
  summarise(frequency = n()) %>%
  arrange(desc(frequency))

damage_frequency %>%
  ggplot(aes(x = reorder(tree_condition, frequency), y=frequency)) +
  geom_bar(stat = "identity") +
  coord_flip() +
   labs(title = "Damage Intensity", x = "Damage type", y = "Frequency")
```

Timeline of storms with service requests\

heat map of trees & serviced trees per neighborhood

```{r}
treemap_neighborhoods <- st_join(tree_map, neighborhood_boundaries)

serviced_neighborhoods <- st_join(serviced_trees, neighborhood_boundaries)
```

```{r}
treemap_counts <- treemap_neighborhoods %>%
  st_drop_geometry() %>%
  count(ntaname, name = "total_trees")

serviced_counts <- serviced_neighborhoods %>%
  st_drop_geometry() %>%
  count(ntaname, name = "serviced_trees")
```

```{r}
neighborhood_counts <- neighborhood_boundaries %>%
  left_join(treemap_counts, by = "ntaname") %>%
  left_join(serviced_counts, by = "ntaname") %>%
  mutate(
    total_trees = replace_na(total_trees, 0),
    serviced_trees = replace_na(serviced_trees, 0)
  )
```

```{r}
centroids <- st_centroid(neighborhood_counts)
```

```{r}
ggplot() +
  geom_sf(
    data = neighborhood_counts,
    aes(fill = total_trees),
    color = "white",
    linewidth = 0.2
  ) +
  geom_sf(
    data = centroids,
    aes(size = serviced_trees),
    color = "white",
    alpha = 0.4
  ) +
  scale_fill_viridis_c(name = "Total Trees") +
  scale_size_area(max_size = 5, name = "Serviced Trees") +
  theme_minimal()
```

```{r}
library(ggplot2)

ggplot(serviced_trees, aes(x = service_request_date)) +
  geom_histogram(binwidth = 7 * 24 * 60 * 60) +  # 7-day bins
  labs(x = "Date", y = "Number of service requests")
```

```{r}
service_requests$service_request_date <- as.POSIXct(
  service_requests$service_request_date,
  format = "%Y-%m-%d %H:%M:%S"
)
```
