---
title: "R Notebook"
output: html_notebook
---

### Joining datasets

#### 1. Join hazard history and service requests to get a list of requests made during and 24 hours after a severe weather event

```{r}
# getting all service requests during and 24 hours after a storm, including overlaps between multiple storms
library(data.table)
setDT(service_requests)
setDT(hazard_history)

storm_service_requests <- hazard_history[service_requests,
                                 on = .(storm_start_date <= service_request_datetime, window_end >= service_request_datetime),
                                 nomatch = 0, 
                                 allow.cartesian = TRUE]
```

```{r}
#select relevant variables
storm_service_requests <- storm_service_requests %>%
  select("storm_event_id", "storm_date", "storm_duration", "storm_name", "storm_issues", "tree_condition", "borough", "address", "service_request_date", "geometry")
```

#### 2. Join storm service requests with tree map data to get species and size of each serviced tree

```{r}
#join by nearest feature - matches serviced tree locations (planting spaces) to the closest tree coordinates given in the tree map
storm_service_requests <- st_as_sf(storm_service_requests)

serviced_trees <- st_join(storm_service_requests, tree_map, join = st_nearest_feature)
```

```{r}
#selecting and rearranging relevant columns
serviced_trees <- serviced_trees %>%
  select("tree_id", "species_common", "species_scientific", "stump_diameter", "tree_condition", "borough", "closest_address", "geometry", "service_request_date", "storm_date", "storm_event_id", "storm_issues")
```

```{r}
#reformatting dates to be POSIXct objects
serviced_trees$service_request_date <- ymd_hms(serviced_trees$service_request_date)
serviced_trees$storm_date <- mdy_hm(serviced_trees$storm_date)
```

```{r}
#merge rows that were counted twice, since some storms happened within 24 hours of each other
serviced_trees <- serviced_trees %>%
  distinct(geometry, service_request_date, .keep_all = TRUE)
```

```{r}
# simplify categories of damage
serviced_trees <- serviced_trees %>%
  mutate(tree_condition = case_when(
    grepl("Limb Down", tree_condition) ~ "Limb Down",
    grepl("Tree Down", tree_condition) ~ "Tree Down",
    grepl("Hanging Limb", tree_condition) ~ "Limb Down",
    grepl("Poor Condition ", tree_condition) ~ "Poor Condition",
    grepl("Tree Uprooted", tree_condition) ~ "Tree Down",  
    TRUE ~ tree_condition))
```

```{r}
#save files
write.csv(storm_service_requests, here("01_data", "1c_intermediate", "storm_service_requests.csv", row.names = FALSE))
write.csv(serviced_trees, here("01_data", "1e_summary", "serviced_trees.csv", row.names = FALSE))
```

\
